### ISSUE TITLE
插件无法安装

### ISSUE THREAD

**Issue by XiaoboAlexander** [dongmuhds/bob-plugin-simpletex-ocr#1]
<img width="260" alt="2023-04-13_16-51-12" src="https://user-images.githubusercontent.com/125983152/231707434-d981f4c7-372e-4b19-9b02-d3908965c60e.png">

**Comment by dongmuhds** [comment]
我在两台mac上都安装正常，我是用的是社区版本。
![image](https://user-images.githubusercontent.com/100669007/232325815-5f1f6460-f453-49c6-94d8-c03303693a20.png)

**Comment by XiaoboAlexander** [comment]
首先，谢谢您的回复，我的电脑配置是：M1 MAX，系统版本13.3.1；Bob版本：1.7.1[118]，pro版。不知道您是否测试的M1芯片的版本！

**Comment by dongmuhds** [comment]
我测试的设备不是m系列的芯片，我的bob停留在最后一版的社区版，编写方法也是按照原来的方法。如果bob的付费版本对插件进行了改动，你可以根据改动的内容修改插件进行使用。
