### ISSUE TITLE
在bob最新版中，可以在插件列表中看到插件但在ocr服务中无法找到。

### ISSUE THREAD

**Issue by moxi000** [dongmuhds/bob-plugin-simpletex-ocr#2]
如题，以至于不能正常使用。
<img width="915" alt="image" src="https://github.com/dongmuhds/bob-plugin-simpletex-ocr/assets/66484370/d843d0a9-4c5d-4c03-badf-3287c754e127">
<img width="746" alt="image" src="https://github.com/dongmuhds/bob-plugin-simpletex-ocr/assets/66484370/a56287ec-b825-4567-86ed-8cfd618ba8d9">

**Comment by dongmuhds** [comment]
![image](https://github.com/dongmuhds/bob-plugin-simpletex-ocr/assets/100669007/f4fd5901-a611-4ade-be89-8d7e83e56cdb)
请在这个位置查看，官方没开开启ocr功能的插件。
